### ISSUE TITLE
Cannot find include agents/bqre1p_parlai_20220819_cicero_2

### ISSUE THREAD

**Issue by ML-Chen** [facebookresearch/diplomacy_cicero#19]
When I run the example command, I get a message "Cannot find include agents/bqre1p_parlai_20220819_cicero_2".

```
(diplomacy_cicero) ubuntu:~/diplomacy/diplomacy_cicero$ python run.py --adhoc --cfg conf/c01_ag_cmp/cmp.prototxt Iagent_one=agents/bqre1p_parlai_20220819_cicero_2.prototxt Iagent_six=agents/ablations/cicero_imitation_only.prototxt power_one=TURKEY

I0104 16:18:44 [run:154] Config: conf/c01_ag_cmp/cmp.prototxt
I0104 16:18:44 [run:155] Overrides: ['Iagent_one=agents/bqre1p_parlai_20220819_cicero_2.prototxt', 'Iagent_six=agents/ablations/cicero_imitation_only.prototxt', 'power_one=TURKEY']
I0104 16:18:44 [run:163] Exp dir: /home/ubuntu/diplomacy_experiments/results/diplomacy/adhoc/2023-01-04T161844.235885/c01_ag_cmp/cmp/Iag@agents_bqre1p_parlai_20220819_cicero_2.prototxt@Iag@ablations_cicero_imitation_only.prototxt@pow_d83d7012
I0104 16:18:44 [run:164] Job status [before run]: Status.NOT_STARTED
Traceback (most recent call last):
  File "run.py", line 165, in <module>
    heyhi.parse_args_and_maybe_launch(main)
  File "/home/ubuntu/diplomacy/diplomacy_cicero/heyhi/run.py", line 122, in parse_args_and_maybe_launch
    maybe_launch(main, exp_root=get_exp_dir(PROJECT_NAME), overrides=overrides, **kwargs)
  File "/home/ubuntu/diplomacy/diplomacy_cicero/heyhi/run.py", line 173, in maybe_launch
    util.run_with_config(main, exp_handle, cfg, overrides, ckpt_dir, log_level)
  File "/home/ubuntu/diplomacy/diplomacy_cicero/heyhi/util.py", line 566, in run_with_config
    task, meta_cfg = conf.load_root_proto_message(config_path, overrides)
  File "/home/ubuntu/diplomacy/diplomacy_cicero/heyhi/conf.py", line 423, in load_root_proto_message
    extra_include_dirs=extra_include_dirs,
  File "/home/ubuntu/diplomacy/diplomacy_cicero/heyhi/conf.py", line 337, in load_proto_message
    include_overides, scalar_overideds = _parse_overrides(overrides, include_dirs=include_dirs)
  File "/home/ubuntu/diplomacy/diplomacy_cicero/heyhi/conf.py", line 110, in _parse_overrides
    value = str(_resolve_include(value, include_dirs, key))
  File "/home/ubuntu/diplomacy/diplomacy_cicero/heyhi/conf.py", line 98, in _resolve_include
    raise ValueError(err_msg)
ValueError: Cannot find include agents/bqre1p_parlai_20220819_cicero_2. Possible typo, known includes:
agents/base_strategy_model
agents/cicero
agents/diplodocus_high
agents/diplodocus_low
agents/repro
agents/searchbot
```

As suggested, I can run the command if I replace `agents/bqre1p_parlai_20220819_cicero_2` in the command with `agents/cicero`, and that's able to simulate the game for a while, although it eventually gets me the following error:

```
  File "/home/ubuntu/diplomacy/diplomacy_cicero/parlai_diplomacy/wrappers/orders.py", line 1110, in _format_input_seq
    assert target_power is not None
AssertionError
```

Thanks for looking at this issue!

**Comment by c-flaherty** [comment]
@ML-Chen, https://github.com/facebookresearch/diplomacy_cicero/pull/22/files fixes your bug around target_power assert! Let us know if anything else causes you trouble :)
