### ISSUE TITLE
Issue installing postman, problem with cannot find CUDA

### ISSUE THREAD

**Issue by yingtaoluo** [facebookresearch/diplomacy_cicero#28]
Hi, I have tried hard solving this but still have no clue. My CUDA is 11.6 and CUDA_HOME is specified. torch.cuda.is_available is True. I not sure which could cause the following questions. Is that because we need to do "conda install --yes pytorch=1.7.1 torchvision cudatoolkit=11.0 -c pytorch" while the cuda version is diffferent?

 Preparing metadata (setup.py) ... done
Requirement already satisfied: torch>=1.4.0 in /home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages (from postman==0.2.2) (1.7.1+cu110)
Requirement already satisfied: typing-extensions in /home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages (from torch>=1.4.0->postman==0.2.2) (4.5.0)
Requirement already satisfied: numpy in /home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages (from torch>=1.4.0->postman==0.2.2) (1.20.3)
Installing collected packages: postman
  Running setup.py develop for postman
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─
        mkdir -p cmake_build/postman && cd cmake_build/postman && cmake -DCMAKE_BUILD_TYPE=Release ../../postman -DPYTHON_EXECUTABLE=/home/yingtao/miniconda3/envs/diplomacy_cicero/bin/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=../../postman/python/postman
        -- pybind11 v2.3.dev1
        -- No CMAKE_CXX_STANDARD set, assuming 11
        --
        -- 3.11.2.0
        -- Could NOT find CUDA (missing: CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (found version "11.6")
        CMake Warning at /home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:31 (message):
          Caffe2: CUDA cannot be found.  Depending on whether you are building Caffe2
          or a Caffe2 dependent library, the next warning / error will give you more
          info.
        Call Stack (most recent call first):
          /home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
          /home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
          CMakeLists.txt:48 (find_package)
        
        
        CMake Error at /home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:90 (message):
          Your installed Caffe2 version uses CUDA but I cannot find the CUDA
          libraries.  Please set the proper CUDA prefixes and / or install CUDA.
        Call Stack (most recent call first):
          /home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
          CMakeLists.txt:48 (find_package)
        
        
        -- Configuring incomplete, errors occurred!
        See also "/home/yingtao/diplomacy_cicero/thirdparty/github/fairinternal/postman/cmake_build/postman/CMakeFiles/CMakeOutput.log".
        See also "/home/yingtao/diplomacy_cicero/thirdparty/github/fairinternal/postman/cmake_build/postman/CMakeFiles/CMakeError.log".
        make: *** [Makefile:9: cmake_build/postman/Makefile] Error 1
        /home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          EasyInstallDeprecationWarning,
        /home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          setuptools.SetuptoolsDeprecationWarning,
        Traceback (most recent call last):
          File "<string>", line 36, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
            main()
          File "/home/yingtao/diplomacy_cicero/thirdparty/github/fairinternal/postman/postman/setup.py", line 33, in main
            test_suite="setup.test_suite",
          File "/home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
            return distutils.core.setup(**attrs)
          File "/home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
          File "/home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
            super().run_command(command)
          File "/home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
            self.install_for_development()
          File "/home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/command/develop.py", line 114, in install_for_development
            self.run_command('build_ext')
          File "/home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
            self.distribution.run_command(command)
          File "/home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
            super().run_command(command)
          File "/home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/home/yingtao/diplomacy_cicero/thirdparty/github/fairinternal/postman/postman/setup.py", line 20, in run
            subprocess.check_call("make develop".split(), cwd="..")
          File "/home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/subprocess.py", line 363, in check_call
            raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command '['make', 'develop']' returned non-zero exit status 2.
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─
ease ../../postman -DPYTHON_EXECUTABLE=/home/yingtao/miniconda3/envs/diplomacy_cicero/bin/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=../../postman/python/postman
    -- pybind11 v2.3.dev1
    -- No CMAKE_CXX_STANDARD set, assuming 11
    --
    -- 3.11.2.0
    -- Could NOT find CUDA (missing: CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (found version "11.6")
    CMake Warning at /home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:31 (message):
      Caffe2: CUDA cannot be found.  Depending on whether you are building Caffe2
      or a Caffe2 dependent library, the next warning / error will give you more
      info.
    Call Stack (most recent call first):
      /home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
      /home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
      CMakeLists.txt:48 (find_package)
    
    
    CMake Error at /home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:90 (message):
      Your installed Caffe2 version uses CUDA but I cannot find the CUDA
      libraries.  Please set the proper CUDA prefixes and / or install CUDA.
    Call Stack (most recent call first):
      /home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
      CMakeLists.txt:48 (find_package)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/home/yingtao/diplomacy_cicero/thirdparty/github/fairinternal/postman/cmake_build/postman/CMakeFiles/CMakeOutput.log".
    See also "/home/yingtao/diplomacy_cicero/thirdparty/github/fairinternal/postman/cmake_build/postman/CMakeFiles/CMakeError.log".
    make: *** [Makefile:9: cmake_build/postman/Makefile] Error 1
    /home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      EasyInstallDeprecationWarning,
    /home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    Traceback (most recent call last):
      File "<string>", line 36, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>

        main()
      File "/home/yingtao/diplomacy_cicero/thirdparty/github/fairinternal/postman/postman/setup.py", line 33, in main
        test_suite="setup.test_suite",
      File "/home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "/home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
        super().run_command(command)
      File "/home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
        self.distribution.run_command(command)
      File "/home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
        super().run_command(command)
      File "/home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/home/yingtao/diplomacy_cicero/thirdparty/github/fairinternal/postman/postman/setup.py", line 20, in run
        subprocess.check_call("make develop".split(), cwd="..")
      File "/home/yingtao/miniconda3/envs/diplomacy_cicero/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', 'develop']' returned non-zero exit status 2.
    [end of output]

**Comment by yingtaoluo** [comment]
Solved by developing on another server. Specifying cuda env variables + installing cudatoolkit seems not useful (do not know why) and I have to have a complete cuda in the usr/local folder.
