### ISSUE TITLE
ModuleNotFoundError: No module named 'fairdiplomacy.pydipcc

### ISSUE THREAD

**Issue by xiang-xiang-zhu** [facebookresearch/diplomacy_cicero#6]
When i run ` python run.py --adhoc --cfg conf/c01_ag_cmp/cmp.prototxt Iagent_one=agents/bqre1p_parlai_20220819_cicero_2.prototxt Iagent_six=agents/ablations/cicero_imitation_only.prototxt power_one=TURKEY`

```Traceback (most recent call last):
  File "run.py", line 15, in <module>
    from fairdiplomacy.agents.base_agent import BaseAgent
  File "/home/zhuhaixiang/diplomacy_cicero/fairdiplomacy/agents/base_agent.py", line 9, in <module>
    from fairdiplomacy.pydipcc import Game
ModuleNotFoundError: No module named 'fairdiplomacy.pydipcc'```

Why does the import of this file have problems

**Comment by adamlerer** [comment]
Have you followed the installation instructions? Looks like you need to run `make dipcc`.
